### PR TITLE
Refactor: class-based AST

### PR DESCRIPTION
**Pull request by Kristoff-starling**
Rewrite the frontend: use classes to represent statements for the sake of various visitors and subsequent optimizations.
Note: codegen visitor hasn't been implemented and thus the pipeline can't be successfully run currently.

### CODE REVIEW

**Comment by livingshade** [comment]
Looks good to me, I will add codegen as soon as possible. 
Can you merge it? cc @Romero027

**Comment by Kristoff-starling** [comment]
btw, the changes outside `compiler/` are made by the formatter so you needn't spare efforts to review them.

**Comment by Romero027** [comment]
thanks! I will take a look later today

**Review by Romero027 — APPROVED** [review]
lgtm, thank you both

**Pull request merged**
